org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.219
neo_version_range=[21.1.1,)
loader_version_range=[4,)

mod_id=mocreatures
mod_name=Mo' Creatures: Aura Edition
mod_license=GNU General Public License v3.0
mod_version=1.21.1-1.0.4-neoforge-port
mod_group_id=dev.multision
mod_authors=meynoik (Aura Edition / 1.21.1 port only), multision, TheidenHD, DrZhark, BlockDaddy, Bloodshot, ACGaming, IcarussOne, xJon
mod_description=Fan-made slop port of Mo' Creatures: Nostalgia Edition from Minecraft 1.20.1 Forge to Minecraft 1.21.1 NeoForge, made mainly for playing with friends. It may contain bugs. It should be safe for normal use in your own worlds, but backups are still recommended for modded saves.
