org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.219
neo_version_range=[21.1.1,)
loader_version_range=[4,)

mod_id=mocreatures
mod_name=Mo' Creatures: Nostalgia Edition
mod_license=GNU General Public License v3.0
mod_version=1.21.1-1.0.0-neoforge-port
mod_group_id=dev.multision
mod_authors=multision, Mo' Creatures Extended Team, Dr. Zhark
mod_description=Mo' Creatures mod port for Minecraft 1.21.1 NeoForge
